Repository global-selfservice/metrics, pull requests merged in 2021-06, with the labels that each got.

#60 chore(deps): update terraform github.com/global-devops-terraform/k8s-metrics to v0.153.0
  metrics.tf
Labels: size/XS

#61 chore(deps): update terraform github.com/global-devops-terraform/k8s-metrics to v0.154.0
  metrics.tf
Labels: size/XS

#62 chore(deps): update terraform github.com/global-devops-terraform/k8s-metrics to v0.156.0
  metrics.tf
Labels: size/XS, ✅ Approved, 🔍 Ready for Review

#63 chore(deps): update terraform github.com/global-devops-terraform/k8s-metrics to v0.157.0
  metrics.tf
Labels: size/XS, ✅ Approved

#64 chore(deps): update terraform github.com/global-devops-terraform/k8s-namespace to v0.20.0
  grafana.tf
Labels: size/XS, ✅ Approved

#65 chore(deps): update terraform github.com/global-devops-terraform/k8s-metrics to v0.159.0
  metrics.tf
Labels: size/XS, ✅ Approved

#66 chore(deps): update terraform github.com/global-devops-terraform/k8s-metrics to v0.160.0
  metrics.tf
Labels: size/XS, 🔍 Ready for Review

#67 chore(deps): update terraform github.com/global-devops-terraform/k8s-metrics to v0.161.0
  metrics.tf
Labels: size/XS, ✅ Approved

#69 fix: Use prefix list
  README.md
  metrics.tf
Labels: size/S, 🔍 Ready for Review

#68 chore(deps): update terraform github.com/global-devops-terraform/global-info to v0.48.0
  common.tf
Labels: size/XS, 🔍 Ready for Review
